### ISSUE TITLE
WebhookUrl is private

### ISSUE THREAD

**Issue by Curdie** [jeroenmaes/log4net.MicrosoftTeams#1]
For various reasons, using XML configuration for log4net is impractical in one of my projects. I configure my logger this way:
```c#
            var teamsAppender = new log4net.MicrosoftTeams.MicrosoftTeamsAppender()
            {
                Name = "TeamsLog",
                Threshold = log4net.Core.Level.Error,
                WebhookUrl = webhookUrl,
                Layout = new log4net.Layout.PatternLayout("%level %logger - %message")
            };

            teamsAppender.ActivateOptions();
            hierarchy.Root.AddAppender(teamsAppender);
```

Unfortunately, this appender has a private "WebhookUrl" property. I've cloned the project and simply set the WebhookUrl property to public instead of private and it works well using this code, but I'd prefer to use a Nuget package rather than add another project to my solution. Would you consider making this property public so the logger can be instantiated in this way? Is there another method of setting this property?

**Comment by jeroenmaes** [comment]
WebhookUrl should be made public, I totally agree. Will fix asap.
