### ISSUE TITLE
Using "level" setting

### ISSUE THREAD

**Issue by eugenpopa** [jeroenmaes/log4net.MicrosoftTeams#6]
Logging messages to teams does not account for<level value="ERROR"  setting within appender or log4net <root element

**Comment by jeroenmaes** [comment]
Can you describe a bit more in detail what is not working and the behaviour you do expect?

**Comment by eugenpopa** [comment]
Hi, 
Log4net has a setting in the appender definition called "level". It should determine the logger to log only messages with a level higher or equal to the setting. E.g. if I set it to "WARN" it should not log any INFO messages, just WARN, ERROR and FATAL. I set mine to ERROR and still got INFO messages logged into Teams channel,
I looked at the code and it seems that this should be done by log4net itself within ActivateOptions().
It might not be a problem with your code after all.

**Comment by eugenpopa** [comment]
Found the problem within my appender settings.
Level is set just for root. Filters should be used within appender.
